# только для разработки бекенда и простого тестирования
spring:
  application:
    name: privateclubbackend

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

# Есть проблемы на локалке
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true


jwt:
  key: ${JWT_SECRET}
  expiration: 6400
telegram:
  botToken: ${BOT_TOKEN}
  authExpirationTime: 3600

s3:
  url: ${S3_URL}
  bucketName: ${S3_BUCKET_NAME}
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  region: ${S3_REGION}