# только для разработки бекенда и простого тестирования
spring:
  application:
    name: privateclubbackend

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

# Есть проблемы на локалке
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true


jwt:
  key: 1DA6EE2E51A27C7D8740FA9AC2F1E808DBA4EFFA7E6C134FE6AB667528CC87AD
  expiration: 6400
telegram:
  botToken: 2200142737:AAFJaXPlfdQZ_sdN8qS73vqEnVTMgzT2V3A
  authExpirationTime: 3600

s3:
  url: https://media.mitrohinayulya.ru #https://s3.timeweb.cloud
  bucketName: d9448f39-de1300a0-194f-4f03-8e6f-fef059f790f3
  accessKey: FT1F73OJ9WR4DG80UZPR
  secretKey: 2oFDIvcOrGguyXCNKcckDnAhaayCMe2JT58MKc2d
  region: ru-1